### ISSUE TITLE
[Research] Create an excel document with all necessary parts and their prices

### ISSUE THREAD

**Issue by Slyde-R** [CyberducksTeam/HACKberry#1]
### Description
- Research the necessary parts and find suitable vendors including their prices
- Check which tools are required and if they are available at GG
- Add all info to a spreadsheet in [this ](https://drive.google.com/drive/folders/1K-2nTi3Mq7XBdJcHd77PQMIqDGN6I6P-?usp=drive_link) folder

### Solution Path

started [spreadsheet](https://docs.google.com/spreadsheets/d/1JPBIhWRU-1c9VdJWHg6YsXxTCGHzu7A7xPABPL-MGSc/edit#gid=2075862474)

still to do:

- [x] #2 
- [ ] send BOM to GG (Cooperation with Würth electronics)

**Comment by sinahsoehner** [comment]
Support in BOM @Slyde-R

**Comment by Slyde-R** [comment]
total w/o PCBs, printed parts and shipping: **244,91**

**Comment by Slyde-R** [comment]
optimize vendor list to reduce shipping and order ASAP
