### ISSUE TITLE
[Execution] Optimize the BOM to save cost and order via spreadsheet

### ISSUE THREAD

**Issue by Slyde-R** [CyberducksTeam/HACKberry#11]
### Objective

Reduce the number of vendors to save on shipping (currently there are 10 different shops)
Also check for reasonable delivery times as this project should not be delayed because of it.

Organize everything reduced spreadsheet for easier ordering

Keep in mind that we want to order at least the parts for two HACKberrys 🍓 

### Additional Information

The part list can be found [here](https://docs.google.com/spreadsheets/d/1JPBIhWRU-1c9VdJWHg6YsXxTCGHzu7A7xPABPL-MGSc/edit#gid=2075862474)

**Comment by daZando** [comment]
Order already done, task outdated.
